# Generated by Django 4.2.7 on 2024-01-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_image', models.ImageField(upload_to='upload/catagory/')),
                ('catagory_name', models.CharField(default='', max_length=100, null=True)),
            ],
        ),
    ]
