# Generated by Django 4.2.7 on 2024-01-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catagory_image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
