# Generated by Django 4.2.7 on 2024-01-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_rename_catagory_image_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='uploads/category/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='uploads/product')),
                ('Product_name', models.CharField(default='', max_length=100, null=True)),
                ('Product_price', models.IntegerField(default=1)),
                ('Product_desc', models.CharField(default='', max_length=100, null=True)),
                ('Product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.category')),
            ],
        ),
    ]
