# Generated by Django 4.2.7 on 2024-01-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_alter_category_category_image_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('mobile', models.BigIntegerField(default=1)),
                ('price', models.IntegerField(default=1)),
                ('quanity', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.product')),
                ('custamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.registration')),
            ],
        ),
    ]
